// $ANTLR : "Gramatica.g" -> "MiLexer.java"$

public interface MiParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ENTERO = 4;
	int REAL = 5;
	int ID = 6;
	int Whitespace = 7;
	int DELIM_PUNTOCOMA = 8;
	int DELIM_PAREN_A = 9;
	int DELIM_PAREN_C = 10;
	int OP_IGUAL = 11;
	int OP_AS = 12;
	int OP_MAS = 13;
	int OP_MENOS = 14;
	int OP_MOD = 15;
	int OP_MUL_DIV = 16;
	int OP_OR = 17;
	int OP_AND = 18;
	int OP_NOT = 19;
	int OP_COMP = 20;
	int OP_IN = 21;
	int OP_OUT = 22;
	int FIN = 23;
	int ASIG_IGUAL = 24;
	int INT_O_REAL = 25;
	int COMP1_2 = 26;
	int NOT_COMP = 27;
	int SEP = 28;
	int OP_MAYQ = 29;
	int OP_MENQ = 30;
	int OP_MAYOI = 31;
	int OP_MENOI = 32;
	int OP_MUL = 33;
	int OP_DIV = 34;
	int TIPOREAL = 35;
	int TIPOENT = 36;
	int LETRA = 37;
	int DIGITO = 38;
	int DELIM_PUNTO = 39;
	int SALTODELINEA = 40;
	int COMP1 = 41;
	int COMP2 = 42;
	int ID_TIPO_OPIN_OPOUT = 43;
	int COMENTARIO = 44;
	int ERRORES = 45;
}
